export const lesson = {
  number: "7.2.2",
  title: "Gather Knowledge: The Lessons Learned Pipeline",
  screens: [
    {
      id: "hook",
      tab: "The trip journal",
      type: "reveal",
      kicker: "Screen 1 — Hook",
      headline: "The details that would have actually helped next time are already gone.",
      lead: "If you journal each day of a trip as it happens, you remember the exact restaurant name, the price, the turn you almost missed. Wait until you're home to write the whole trip from memory, and it blurs into “the weather was nice and the food was good” — the details that would have actually helped next time are already gone.",
      heading: "If you journal each day of a trip as it happens, you remember the exact restaurant name, the price, the turn you almost missed. Wait until you're home to write the whole trip from memory, and it blurs into “the weather was nice and the food was good” — the details that would have actually helped next time are already gone.",
      cta: "Reveal the pipeline",
      image: "trip-journal",
      reveal: {
        title: "Gathering knowledge is a pipeline, not an event",
        text: "Gathering knowledge is a pipeline, not an event. Enabler 7.2 is widely caricatured as “the lessons learned meeting at the end” — but the professional version is a five-stage pipeline that runs the project's whole length. A lesson recorded in week six carries the names, numbers, and causal chain that the same lesson “remembered” in week thirteen has already lost.",
        image: "trip-journal",
      },
    },
    {
      id: "pipeline",
      tab: "Five-stage pipeline",
      type: "accordion",
      kicker: "Screen 2 — The Five-Stage Pipeline",
      headline: "The Five-Stage Pipeline",
      heading: "Five stages carry a lesson from the moment it happens to the moment it actually changes how the next project runs. Click each to explore.",
      intro: "",
      image: "five-stage-pipeline",
      items: [
        { title: "Continuous Capture", text: "Lessons are logged when they happen — in retrospectives, after incidents, when a risk fires or a variance surprises." },
        { title: "The Lessons Learned Register", text: "The project's living log, and a formal project artifact in PMBOK® 8." },
        { title: "The Final Session at Closure", text: "Not the first time lessons are discussed, but the time they are curated — validated, de-duplicated, generalized from this project's specifics into recommendations another project can use, and prioritized so the repository receives signal rather than noise." },
        { title: "The Repository", text: "The organizational store, owned beyond the project — usually by the PMO — where curated lessons become searchable assets." },
        { title: "Reuse", text: "The next project retrieves at planning, and processes and templates change." },
      ],
      after: { label: "Defining test", text: "A lesson is not “learned” when it is written; it is learned when the next project behaves differently because of it." },
    },
    {
      id: "register",
      tab: "Nine fields",
      type: "accordion",
      kicker: "Screen 3 — The Register's Structure: Nine Fields",
      headline: "A register with structure is a database.",
      heading: "A register of free-text war stories is a diary. A register with structure is a database. Click each field to explore.",
      intro: "",
      image: "nine-field-register",
      items: [
        { title: "Identifier and Date", text: "So the entry can be located and placed in time." },
        { title: "Category", text: "From a shared taxonomy — estimating, vendor management, stakeholder communication, technical, process." },
        { title: "Situation", text: "What happened, factually." },
        { title: "Impact", text: "What it cost or saved, in numbers where possible." },
        { title: "Root Cause", text: "When analysis was done — the difference between “testing started late” and “testing started late because environment provisioning has no owner” is the difference between an anecdote and a fix." },
        { title: "Recommendation", text: "Written as a generalized, actionable instruction to a future team." },
        { title: "Owner", text: "Who is accountable for this entry." },
        { title: "Status", text: "Where it currently stands." },
        { title: "Tags", text: "The searchable handles that let a PM three years from now, planning a different rollout, find this entry in seconds." },
      ],
      after: { label: "Positive lessons", text: "Positive lessons get equal standing with failures — what went right, and why, is the cheaper half of the learning, and the half teams forget to write down." },
      quiz: {
        question: "Scenario: A lessons learned entry reads: “Testing started late.” No root cause, recommendation, or tags are included. A different project manager, two years later, searches the repository for insights on testing delays but never finds this entry. What does this scenario best illustrate?",
        answers: [
          "The entry is fine as written, since the fact itself (“testing started late”) is accurate",
          "The issue is that positive lessons weren't included alongside this negative one",
          "The entry should have been added to the risk register instead of the lessons learned register",
          "Searchability failure — without root cause, a generalized recommendation, and tags, the entry is an anecdote nobody can find or act on, rather than a usable fix",
        ],
        correct: 3,
        correctFeedback: "Correct! This is exactly the second great failure mode of organizational learning — a lesson that exists but can't be found or acted on. Without root cause, a generalized recommendation, and tags, “testing started late” is an anecdote, not a fix, and it will stay invisible to exactly the person who needed it.",
        incorrectFeedback: "Reconsider — the fact stated is accurate but incomplete as a usable lesson; this isn't about missing positive lessons elsewhere, and it isn't a risk register issue — it's specifically a structure and searchability problem within the lessons learned entry itself.",
      },
    },
    {
      id: "records",
      tab: "Where lessons hide",
      type: "accordion",
      kicker: "Screen 4 — Where Lessons Hide: The Project's Own Records",
      headline: "The final session begins with a sweep, not a brainstorm.",
      heading: "At closure, the richest sources of lessons are the registers the project has already been keeping. The final session begins with a sweep, not a brainstorm. Click each source to explore.",
      intro: "",
      image: "records-sweep",
      items: [
        { title: "The Issue Log", text: "Records what actually went wrong, how it was resolved, and how long resolution took. Any issue that recurred is a flashing arrow pointing at a process problem." },
        { title: "The Agile Track's Impediment Backlog", text: "Records what blocked the team and what removed the blocks — a ready-made map of organizational friction." },
        { title: "The Risk Register", text: "Shows which risks fired and whether the planned responses worked — raw material for improving the organization's risk taxonomy and response playbooks." },
        { title: "The Change Log and Variance Analyses", text: "The change log explains what changed and why; variance analyses explain where estimates broke." },
        { title: "Quality/Test Records and Vendor Records", text: "Quality and test records show where defects clustered; vendor records hold the negotiation and performance story." },
      ],
      quiz: {
        question: "Scenario: At project closure, a facilitator opens the lessons learned session by asking the team to brainstorm from memory what they think went well and poorly, without first reviewing the issue log, risk register, or other project records. What does this approach risk missing?",
        answers: [
          "Lessons that memory alone would miss, along with the evidence (dates, numbers, documents) that makes a lesson trustworthy to a future reader",
          "Nothing significant — brainstorming from memory is the standard and most effective way to begin a lessons learned session",
          "The session should have started with positive lessons specifically before addressing negative ones",
          "The impediment backlog, since that source is only relevant to agile projects and can be safely skipped in any case",
        ],
        correct: 0,
        correctFeedback: "Correct! Sweeping the project's own records first does two things a memory-only brainstorm can't: it surfaces lessons nobody would think to mention unprompted, and it grounds every lesson in actual evidence, which is what makes a future reader trust it.",
        incorrectFeedback: "Reconsider — this isn't about which lesson type comes first, and the impediment backlog is relevant whenever the project used adaptive practices, not just always skippable; the real risk here is starting from memory rather than the records the project already has.",
      },
    },
    {
      id: "exam",
      tab: "Exam lens",
      type: "reveal",
      kicker: "Screen 5 — Synthesis (Exam Lens)",
      headline: "The entries written in the moment were always the ones actually worth keeping.",
      heading: "Back to that trip journal one more time — because the entries written in the moment were always the ones actually worth keeping.",
      cta: "Reveal the exam lens",
      image: "exam-journal",
      reveal: {
        title: "Synthesis (Exam Lens)",
        text: "Gathering knowledge is a five-stage pipeline: continuous capture, the lessons learned register, the final curating session at closure, the organizational repository, and reuse — where a lesson is only truly “learned” once the next project behaves differently because of it. The register's structure is what makes it usable: identifier and date, category, situation, impact, root cause, recommendation, owner, status, and tags — with positive lessons carrying equal standing. And the richest source of lessons at closure is the project's own records — the issue log, impediment backlog, risk register, change log, variance analyses, quality/test records, and vendor records — swept, not brainstormed from memory.",
        bullets: [
          "Five-stage pipeline: continuous capture, lessons learned register, final curating session, repository, reuse",
          "A lesson is “learned” only when the next project actually behaves differently because of it — not when it's simply written down",
          "Nine register fields: identifier/date, category, situation, impact, root cause, recommendation, owner, status, tags — the fix for lessons that exist but can't be found",
          "Positive lessons deserve equal standing with failures",
          "The final session begins by sweeping existing project records (issue log, impediment backlog, risk register, change log, variance analyses, quality/test/vendor records), not brainstorming from memory",
        ],
        image: "exam-journal",
      },
    },
  ],
};
